### ISSUE TITLE
Breaks in git worktree

### ISSUE THREAD

**Issue by sellout** [47deg/sbt-microsites#117]
If I try to load the sbt-microsites plugin on a git worktree in a different dir than my original clone, I get an error like
```
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1245)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:88)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:139)
	at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:84)
	at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
	at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
	at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:35)
	at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
	at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sellout** [comment]
So, the root cause of this seems to be [a bug in JGit](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475) with [an unmerged “PR”](https://git.eclipse.org/r/#/c/67873/). Which is used by sbt/sbt-git, which is used by sbt/sbt-ghpages, which is used here.

**Comment by raulraja** [comment]
@sellout Would using ConsoleGit instead of JGit help as a workaround for this issue? https://github.com/sbt/sbt-git/blob/5c72a29953c529b29f39e1d0e771406a4c05390f/src/main/scala/com/typesafe/sbt/SbtGit.scala#L112

**Comment by sellout** [comment]
@raulraja Maaaaaaaybe … I’m not sure if I’m setting that correctly. I tried
```scala
SbtGit.GitKeys.gitRunner := sbtgit.ConsoleGitRunner
```
both at the top level of my build.sbt, and also in my `standardSettings` (which is used by every subproject).

**Comment by raulraja** [comment]
@juanpedromoreno any ideas? Maybe one of those `in ThisBuild` ^^^

**Comment by juanpedromoreno** [comment]
Nop, no idea why it's not possible to override that sbt config :( . I'd need more time to look at this issue, and a way to reproduce it.
