### ISSUE TITLE
Error on conflicting cats versions

### ISSUE THREAD

**Issue by cquiroz** [47deg/sbt-microsites#256]
I'm facing this exception due to conflicts on cats versions:

This is observed with `sbt-microsites` 0.7.15

```
[error] java.lang.NoSuchMethodError: cats.instances.package$list$.catsStdInstancesForList()Lcats/TraverseFilter;
[error] 	at sbtorgpolicies.io.FileWriter.copyMultipleFiles$1(FileWriter.scala:85)
[error] 	at sbtorgpolicies.io.FileWriter.$anonfun$copyFilesRecursively$2(FileWriter.scala:89)
[error] 	at scala.util.Either.flatMap(Either.scala:338)
[error] 	at sbtorgpolicies.io.FileWriter.copyFilesRecursively(FileWriter.scala:88)
[error] 	at microsites.util.MicrositeHelper.createResources(MicrositeHelper.scala:68)
[error] 	at microsites.MicrositeAutoImportSettings.$anonfun$micrositeTasksSettings$1(MicrositeKeys.scala:242)
```

It seems this is due to `org-policies-core` which still uses cats 0.9.0

```
[warn] 	* org.typelevel:cats-core_2.12:1.0.1 is selected over {0.9.0, 1.0.0}
[warn] 	    +- org.typelevel:cats-effect_2.12:0.8                 (depends on 1.0.1)
[warn] 	    +- io.github.cquiroz:kuyfi_2.12:0.8.2                 (depends on 1.0.1)
[warn] 	    +- org.tpolecat:atto-core_2.12:0.6.1                  (depends on 1.0.0)
[warn] 	    +- org.typelevel:mouse_2.12:0.15                      (depends on 1.0.0)
[warn] 	    +- org.typelevel:cats-laws_2.12:0.9.0 ()              (depends on 0.9.0)
[warn] 	    +- org.typelevel:cats_2.12:0.9.0 ()                   (depends on 0.9.0)
[warn] 	    +- org.typelevel:cats-jvm_2.12:0.9.0 ()               (depends on 0.9.0)
[warn] 	    +- com.47deg:org-policies-core_2.12:0.8.17 ()         (depends on 0.9.0)
```

**Comment by jaksah** [comment]
This happens for me as well after adding `sbt-bloop:1.2.5` plugin

**Comment by calvellido** [comment]
Sadly, this is a long-standing issue that, after [some other attempts](https://github.com/47deg/sbt-org-policies/pull/1136), we only could get rid off by [stopping depending](https://github.com/47deg/sbt-microsites/issues/239) on `sbt-org-policy`, which is not an easy task.

**Comment by Krever** [comment]
Is there any workaround for this?

**Comment by juanpedromoreno** [comment]
Yes, hopefully, we get a fix soon. I'll let you know.

**Comment by juanpedromoreno** [comment]
FYI: @cquiroz @jaksah @Krever The new version of the plugin, **0.9.0** fixes the issue.

**Comment by Krever** [comment]
Yes, I confirmed this few hours ago myself as well. Thanks a lot!

wt., 26 lut 2019 o 16:15 Juan Pedro Moreno <notifications@github.com>
napisał(a):
