### ISSUE TITLE
Issues with 0.9.0 and Scalameta mdoc

### ISSUE THREAD

**Issue by jdegoes** [47deg/sbt-microsites#305]
I think there's an issue with the way scalameta-mdoc is listed as a dependency. Upgrading to 0.9.0 caused several breakages, including:

 - `sbt-explicit-dependencies` failing the build because `scalameta-mdoc` is unused
 - `publish` failing on 2.13 because `scalameta-mdoc` has no such release

**Comment by rafaparadela** [comment]
I'm taking a look at this later. Thanks @jdegoes

**Comment by jdegoes** [comment]
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalameta#mdoc_2.13.0-M5;1.2.10: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at 
```

And also:

<https://travis-ci.org/scalaz/scalaz-zio/jobs/506929362>

@rafaparadela Thank you for any help you can provide!

**Comment by jdegoes** [comment]
We needed to upgrade to 0.9.0 to fix a transitive issue with the Cats dependency (recently fixed, I believe).

**Comment by jdegoes** [comment]
More information:

 - `skip in publish := true` is set in the microsite project
 - `microsite` is the only project using the plug-in
 - Despite the above and also trying to exclude scalameta mdoc from transitive dependencies, `publishLocal` still fails due to unresolved dependency

**Comment by rafaparadela** [comment]
I'm still on it. Must be something related to Travis settings, because locally I'm able to run `makeMicrosite` succesfully:

```bash
sbt:scalaz-microsite> makeMicrosite
[info] Compiling 61 Scala sources and 1 Java source to /Users/rafaparadela/code/playground/scalaz-zio/core/jvm/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 3 Scala sources to /Users/rafaparadela/code/playground/scalaz-zio/interop-shared/jvm/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /Users/rafaparadela/code/playground/scalaz-zio/interop-java/jvm/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /Users/rafaparadela/code/playground/scalaz-zio/interop-future/jvm/target/scala-2.12/classes ...
[info] Compiling 3 Scala sources to /Users/rafaparadela/code/playground/scalaz-zio/interop-reactiveStreams/jvm/target/scala-2.12/classes ...
[info] Compiling 3 Scala sources to /Users/rafaparadela/code/playground/scalaz-zio/interop-scalaz7x/jvm/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 3 Scala sources to /Users/rafaparadela/code/playground/scalaz-zio/interop-cats/jvm/target/scala-2.12/classes ...
[info] Done compiling.
[info] Done compiling.
[info] Done compiling.
[info] Done compiling.
[info] Running tut.TutMain /Users/rafaparadela/code/playground/scalaz-zio/microsite/src/main/tut /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll .*\.(md|markdown|txt|htm|html) -deprecation -encoding UTF-8 -explaintypes -Yrangepos -feature -Xfuture -language:higherKinds -language:existentials -unchecked -Xsource:2.13 -Xfatal-warnings -opt-warnings -opt:l:inline -opt-inline-from:<source> -Ypartial-unification -Yno-adapted-args -Xplugin:/Users/rafaparadela/.ivy2/cache/org.spire-math/kind-projector_2.12/jars/kind-projector_2.12-0.9.9.jar -Xplugin:/Users/rafaparadela/.ivy2/cache/com.github.ghik/silencer-plugin_2.12/jars/silencer-plugin_2.12-1.3.1.jar
[tut] compiling: /Users/rafaparadela/code/playground/scalaz-zio/microsite/src/main/tut/advanced/performance.md
[tut] compiling: /Users/rafaparadela/code/playground/scalaz-zio/microsite/src/main/tut/advanced/error_model.md
...
[tut] compiling: /Users/rafaparadela/code/playground/scalaz-zio/microsite/src/main/tut/usecases/concurrency.md
[info] Running tut.TutMain /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll/_extra_md /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll .*\.(md|markdown|txt|htm|html) -deprecation -encoding UTF-8 -explaintypes -Yrangepos -feature -Xfuture -language:higherKinds -language:existentials -unchecked -Xsource:2.13 -Xfatal-warnings -opt-warnings -opt:l:inline -opt-inline-from:<source> -Ypartial-unification -Yno-adapted-args -Xplugin:/Users/rafaparadela/.ivy2/cache/org.spire-math/kind-projector_2.12/jars/kind-projector_2.12-0.9.9.jar -Xplugin:/Users/rafaparadela/.ivy2/cache/com.github.ghik/silencer-plugin_2.12/jars/silencer-plugin_2.12-1.3.1.jar
[info] Configuration file: /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll/_config.yml
[info]             Source: /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll
[info]        Destination: /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/jekyll
[info]  Incremental build: disabled. Enable with --incremental
[info]       Generating... 
[info]                     done in 6.186 seconds.
[info]  Auto-regeneration: disabled. Use --watch to enable.
[success] Total time: 141 s, completed Mar 15, 2019 4:01:49 PM
```

And I also could run the microsite with no issue:

```bash
Rafas-MacBook-Pro:jekyll rafaparadela$ cd /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll
Rafas-MacBook-Pro:jekyll rafaparadela$ jekyll serve
Configuration file: /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll/_config.yml
            Source: /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll
       Destination: /Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 4.413 seconds.
 Auto-regeneration: enabled for '/Users/rafaparadela/code/playground/scalaz-zio/microsite/target/scala-2.12/resource_managed/main/jekyll'
    Server address: http://127.0.0.1:4000/scalaz-zio/
  Server running... press ctrl-c to stop.
```

![https://i.ibb.co/M6m2tWf/Screen-Shot-2019-03-15-at-4-10-25-PM.png](https://i.ibb.co/M6m2tWf/Screen-Shot-2019-03-15-at-4-10-25-PM.png)

**Comment by zakpatterson** [comment]
I think we're running into the same issue here, where our project fails to just compile on 2.13 -- not running mdoc:

build error: https://travis-ci.com/pauljamescleary/scala-pet-store/jobs/214042144#L411

**Comment by juanpedromoreno** [comment]
We might need to wait until `mdoc` is cross-compiled with Scala 2.13: https://github.com/scalameta/mdoc/pull/173

**Comment by olafurpg** [comment]
Scala 2.13 support in mdoc is being released right now by https://travis-ci.org/scalameta/mdoc/builds/576584631

However, until now it should already have been possible to upgrade a builds to 2.13 regardless of mdoc if you're OK with generating the docs only for 2.12.

When using sbt-mdoc, the `org.scalameta:mdoc` dependency is added as a regular library dependency to the enabled sbt project. For projects that generate docs only for 2.12, you should be able to avoid the resolution error by setting
```diff
lazy val docs = project.settings(
+  crossScalaVersions := List("2.12.8"),
  ...
).enablePlugin(MdocPlugin)
```

With this setup, you will still get a resolution error when running the following sequence of commands
```
> ++2.13.0
> test
// ERROR in docs/test
```

The following should work however
```
> ++2.13.0 test
// OK because docs/test is skipped because crossScalaVersions does not contain 2.13.0
```

When running sbt from CI, it's important to quote together `++2.13.0` and the command. For example `sbt ++2.13.0 test` will cause a resolution error while `sbt "++2.13.0 test"` should work OK.

**Comment by juanpedromoreno** [comment]
Thanks @olafurpg , for such as amazing work on `mdoc` and the clarification on how to configure/run these _docs_ artifacts :)

**Comment by juanpedromoreno** [comment]
mdoc is now crossbuild for Scala 2.13.x. We can close this issue.
